### ISSUE TITLE
Bate-papo do desenvolvedor do simulador Yugioh.

### ISSUE THREAD

**Issue by PixelatedProphet** [Gian-UC/yugioh-game#1]
Estamos interessados no seu projeto e gostaríamos que você participasse do nosso chat de desenvolvimento. Temos desenvolvedores de Salvation, Edopro, Dueling Book, Dueling Nexus e outros aqui.

eu usei o Google Tradutor
https://discord.gg/wUjrTS4

**Comment by Gian-UC** [comment]
Olá, irei entrar no grupo do DS.
